apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"   # to make sure it runs before services
      name: 'keda-operator-{{ .name }}'
    spec:
      project: cluster-addons
      destination:
        server: '{{ .server }}'
        namespace: keda
      source:
        repoURL: https://kedacore.github.io/charts
        chart: keda
        targetRevision: 2.18.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
