apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"   # to make sure it runs before services
      name: 'prometheus-operator-{{ .name }}'
    spec:
      project: cluster-addons
      destination:
        server: '{{ .server }}'
        namespace: monitoring
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 77.13.0
        helm:
          values: |
            # Install the operator, but disable the default managed components
            prometheusOperator:
              enabled: true
            # Disable the Prometheus instances that the chart would create
            prometheus:
              enabled: false
            # Disable Alertmanager
            alertmanager:
              enabled: false
            # Disable Grafana
            grafana:
              enabled: false
            # Disable exporters / extra components
            kubeStateMetrics:
              enabled: false
            nodeExporter:
              enabled: false
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
