apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"   # to make sure it runs before services
      name: 'sealed-secrets-controller-{{.name}}'
    spec:
      destination:
        namespace: kube-system
        server: '{{.server}}'
      project: clusters-infrastructure
      source:
        chart: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.15.4
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
