# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://argoproj.github.io/argo-helm
#     targetRevision: 8.3.0
#     chart: argo-cd
#     helm:
#       parameters:
#         - name: server.insecure
#           value: "true"
#         - name: server.service.type
#           value: "ClusterIP"
#         - name: server.service.portHttp
#           value: "80"
#   destination:
#     name: in-cluster
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
