apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/yoav7000/platform-gitops.git
              revision: main
              files:
                - path: environments/*/config.yaml
              pathParamPrefix: env
              values:
                env_name: "{{index .env.path.segments 1}}"
                namespace: "{{ .namespace }}"
          - git:
              repoURL: https://github.com/yoav7000/platform-gitops.git
              revision: main
              files:
                - path: services/*/chart-config.yaml
              pathParamPrefix: app
              # values:
              #   service_name: "{{index .app.path.segments 1}}"

  template:
    metadata:
      name: '{{index .app.path.segments 1}}-{{.values.env_name}}'
    spec:
      project: '{{.env.values.env_name}}'
      sources:
        - repoURL: '{{ .app.chart.repoURL }}'
          targetRevision: '{{.app.chart.targetRevision}}'
          # path: '{{.chart.path}}'
          helm:
            valueFiles:
              - $values/services/{{.app.values.service_name}}/values/{{.env.values.env_name}}.yaml
        - repoURL: https://github.com/yoav7000/platform-gitops.git
          targetRevision: main
          ref: values
      destination:
        name: '{{ .env.cluster }}'
        namespace: '{{ .env.values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true