apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/yoav7000/platform-gitops.git
              revision: main
              files:
                - path: environments/*/config.yaml
              pathParamPrefix: env
              values:
                env_name: "{{index .env.path.segments 1}}"
          - git:
              repoURL: https://github.com/yoav7000/platform-gitops.git
              revision: main
              files:
                - path: services/*/chart-config.yaml
              pathParamPrefix: app
              values:
                service_name: "{{index .app.path.segments 1}}"
                chart_url: "{{.chart.repoURL}}"
                chart_revision: "{{.chart.targetRevision}}"
                chart_path: "{{.chart.path}}"

  template:
    metadata:
      name: '{{.app.values.service_name}}-{{.env.values.env_name}}'
    spec:
      project: '{{.env.values.env_name}}'
      sources:
        - repoURL: {{.values.service_name}}
          targetRevision: {{.app.chart.targetRevision}}
          path: {{.chart.path}}
          helm:
            valueFiles:
              - $values/services/{{.app.values.service_name}}/values/{{.env.values.env_name}}.yaml
        - repoURL: https://github.com/yoav7000/platform-gitops.git
          targetRevision: main
          ref: values
      destination:
        name: {{ .env.cluster }}
        namespace: {{ .env.namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true