apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-by-env
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                # Go over all environmets that have a config.yaml file
                - git:
                    repoURL: "https://github.com/yoav7000/platform-gitops.git"
                    revision: main
                    files:
                      - path: environments/**/config.yaml
                    pathParamPrefix: env
                    values:
                      env_name:  "{{ index .env.path.segments 1 }}"

                # Go over all services that have a chart-config.yaml file
                - git:
                    repoURL: "https://github.com/yoav7000/platform-gitops.git"
                    revision: main
                    files:
                      - path: services/**/chart-config.yaml
                    pathParamPrefix: svc
                    values:
                      service_name: "{{ .path.basename }}"

          # Go over all services that have a values.yaml file for the given environment
          - git:
              repoURL: "https://github.com/yoav7000/platform-gitops.git"
              revision: main
              files:
                - path: services/{{ index .svc.path.segments 1 }}/envs/{{ index .env.path.segments 1 }}/values.yaml
              pathParamPrefix: vals
              values:
                values_file_path: services/{{ index .svc.path.segments 1 }}/envs/{{ index .env.path.segments 1 }}/values.yaml

  template:
    metadata:
      name: "{{ index .svc.path.segments 1 }}-{{ .values.env_name }}"
    spec:
      project: '{{.values.env_name}}'
      sources:
        - repoURL: https://github.com/yoav7000/platform-gitops.git
          targetRevision: main
          ref: values
        - repoURL: '{{ .chart.repoURL }}'
          targetRevision: '{{ .chart.targetRevision }}'
          path: '{{.chart.path}}'
          helm:
            valueFiles:
              - $values/services/{{index .svc.path.segments 1}}/envs/{{.values.env_name}}/values.yaml
      destination:
        name: '{{ .cluster.name }}'
        namespace: '{{ .cluster.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
